export const assets_data = {
  assets: [
    {
      id: 1,
      name: 'BTC',
      currency: 'USD',
      last_trade: '$63,000.00',
      image: '/cryptocurrencycolorbtc.svg',
      hour_24_change: '-$1.426.18',
      hour_24_change_percent: '-2.21%',
    },
    {
      id: 2,
      name: 'ETH',
      currency: 'USD',
      last_trade: '$3,408.90',
      image: '/cryptocurrencycoloreth.svg',
      hour_24_change: '-$11.20',
      hour_24_change_percent: '-0.33%',
    },

    {
      id: 3,
      name: 'DOGE',
      currency: 'USD',
      last_trade: '$0.15',
      image: '/cryptocurrencycolordoge.svg',
      hour_24_change: '+$0.02',
      hour_24_change_percent: '+15.75%',
    },
    {
      id: 4,
      name: 'ALGO',
      currency: 'USD',
      last_trade: '$0.15',
      image: '/cryptocurrencycoloralgo.svg',
      hour_24_change: '$0.00',
      hour_24_change_percent: '+0.00%',
    },

    {
      id: 5,
      name: 'DOT',
      currency: 'USD',
      last_trade: '$5.64',
      image: '/cryptocurrencycolordot.svg',
      hour_24_change: '$0.00',
      hour_24_change_percent: '+0.00%',
    },
    {
      id: 6,
      name: 'UNI',
      currency: 'USD',
      last_trade: '$9.79',
      image: '/tokenbrandeduni.svg',
      hour_24_change: '$0.00',
      hour_24_change_percent: '+0.00%',
    },
    {
      id: 7,
      name: 'COMP',
      currency: 'USD',
      last_trade: '$45.67',
      image: '/cryptocurrencycolorcomp.svg',
      hour_24_change: '-$0.44',
      hour_24_change_percent: '-0.95%',
    },
  ],
};
